name: Build and package Hug AI Chat

on:
  push:
    branches: [master]

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
           python-version: '3.10'
           
      - name: add requeriments.txt
        run: pip freeze > requirements.txt

      - name: Install dependencies (including pyinstaller)
        run: pip install -r requirements.txt pyinstaller

      - name: Package with PyInstaller
        run: pyinstaller src/main.py

      - name: Upload .exe package
        uses: actions/upload-artifact@v3
        with:
           name: exe-package
           path: dist/your_hug_ai_chat_script.exe