name: Build and package Hug AI Chat

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build --build-arg BUILDER=python:3.10 -t hug-ai-chat:latest .

      - name: Create .deb package
        run: |
          docker run -v $PWD:/app hug-ai-chat:latest dpkg-buildpackage -b -us -uc

      - name: Upload .deb package
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: dist/hug_ai_chat.deb

      - name: Create .exe package
        run: |
          docker run -v $PWD:/app hug-ai-chat:latest pyinstaller --onefile --windowed hug_ai_chat/main.py

      - name: Upload .exe package
        uses: actions/upload-artifact@v3
        with:
          name: exe-package
          path: dist/hug_ai_chat.exe
